steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-west1-docker.pkg.dev/$PROJECT_ID/demo-app-docker-repo/nginx-hello-world', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-west1-docker.pkg.dev/$PROJECT_ID/demo-app-docker-repo/nginx-hello-world']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'nginx-hello-world',
      '--image', 'us-west1-docker.pkg.dev/$PROJECT_ID/demo-app-docker-repo/nginx-hello-world',
      '--region', 'us-west1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

